# Generated by Django 6.0 on 2026-01-02 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=220),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Industries",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=160)),
                (
                    "message",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)]
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_handled", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("impressum", "Impressum"),
                            ("datenschutz", "Datenschutz"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "content",
                    models.TextField(
                        help_text="You can paste formatted text here.",
                        validators=[django.core.validators.MinLengthValidator(20)],
                    ),
                ),
                ("meta_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "meta_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=240)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("short_description", models.CharField(max_length=220)),
                (
                    "icon",
                    models.CharField(blank=True, default="Briefcase", max_length=40),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="TradeGate Consultants", max_length=120),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Strategy. Execution. Growth.",
                        max_length=180,
                    ),
                ),
                (
                    "primary_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "hero_title",
                    models.CharField(
                        default="Cross-border growth with clarity.", max_length=120
                    ),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="We help companies enter markets, build partnerships, and execute with confidence.",
                        max_length=220,
                    ),
                ),
                (
                    "hero_cta_label",
                    models.CharField(default="Contact us", max_length=40),
                ),
                ("hero_cta_url", models.CharField(default="/contact/", max_length=200)),
                ("meta_title", models.CharField(blank=True, default="", max_length=70)),
                (
                    "meta_description",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("og_image_url", models.URLField(blank=True, default="")),
                ("brand_primary", models.CharField(default="#0B1220", max_length=20)),
                ("brand_accent", models.CharField(default="#C6A15B", max_length=20)),
                ("brand_muted", models.CharField(default="#94A3B8", max_length=20)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
