# Generated by Django 5.0.2 on 2026-02-03 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=50)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("anchor", "Homepage section (#anchor)"),
                            ("internal", "Internal page (named URL)"),
                            ("external", "External URL"),
                        ],
                        default="anchor",
                        max_length=20,
                    ),
                ),
                ("anchor", models.SlugField(blank=True, default="")),
                ("url_name", models.CharField(blank=True, default="", max_length=80)),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        default="",
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=10)),
                ("is_cta", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Navigation Item",
                "verbose_name_plural": "Navigation",
                "ordering": ("order", "label"),
            },
        ),
        migrations.AddField(
            model_name="inquiry",
            name="budget_range",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="consent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="contact_method",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="country",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="service_interest",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="timeline",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="inquiry",
            name="website",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_line1",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="city",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="country",
            field=models.CharField(blank=True, default="Germany", max_length=80),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="facebook_url",
            field=models.URLField(
                blank=True,
                default="",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                default="",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_url",
            field=models.URLField(
                blank=True,
                default="",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="x_url",
            field=models.URLField(
                blank=True,
                default="",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
