# Generated by Django 5.0.2 on 2026-02-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_navigationitem_inquiry_budget_range_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
