# Generated by Django 5.0.2 on 2026-02-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_inquiry_budget_range_inquiry_company_name_and_more"),
        ("website", "0003_sitesettings_updated_at"),
    ]

    operations = []
