# Generated by Django 5.0.2 on 2026-02-09 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_repair_missing_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="country",
            field=models.CharField(blank=True, default="Germany", max_length=80),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="facebook_url",
            field=models.URLField(
                blank=True,
                default="",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                default="",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="whatsapp_url",
            field=models.URLField(
                blank=True,
                default="",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="x_url",
            field=models.URLField(
                blank=True,
                default="",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
