# Generated by Django 5.0.2 on 2026-06-09 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_tradefairopportunity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradefairopportunity",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="",
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
