"""
Django settings for tradegate project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# =========================
# 1) Core Python imports
# =========================
from pathlib import Path
import os

# =========================
# 2) Project base directory
# =========================
# BASE_DIR is the top-level project folder.
# We use it to build absolute paths reliably across environments (Linux/Windows/Mac).
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================
# 3) Environment variables
# =========================
# python-dotenv loads variables from a .env file into your environment.
# This is best practice for secrets and environment-specific configuration.
from dotenv import load_dotenv

# Load ".env" from the project root (same folder where manage.py lives).
load_dotenv(BASE_DIR / ".env")

# =========================
# 4) Security & basic config
# =========================
# SECURITY WARNING: keep the secret key used in production secret!
# In production, you should read this from .env:
# SECRET_KEY = os.getenv("SECRET_KEY")
SECRET_KEY = "django-insecure-kr31o@o==ou8zz)3d0ol)==p(j=lw2c0#r@6ao!016t^7h#7@o"

# DEBUG=True shows detailed error pages and should NEVER be enabled in production.
DEBUG = True

# Hosts allowed to serve the site.
# Add your domain(s) or server IP here when deploying.
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# =========================
# 5) Application definition
# =========================
# INSTALLED_APPS tells Django which apps are active for this project.
INSTALLED_APPS = [
    # Contrib apps = built-in Django functionality.
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Sites framework: useful for multi-site setups and some third-party packages.
    "django.contrib.sites",

    # Your local app where pages/templates/views live.
    "website",
]

# MIDDLEWARE is a pipeline: each middleware can process requests/responses.
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Where Django looks for the root URL routes file.
ROOT_URLCONF = "tradegate.urls"

# =========================
# 6) Templates configuration
# =========================
# This block defines how Django finds and renders HTML templates.
#
# IMPORTANT FIX:
# Previously you had:
#   TEMPLATES[0]["DIRS"] = ...
# above the TEMPLATES definition, causing:
#   NameError: name 'TEMPLATES' is not defined
#
# Correct approach: set DIRS inside the TEMPLATES dict itself.
TEMPLATES = [
    {
        # Django's built-in template engine
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        # DIRS = extra template folders (outside app/templates).
        # We keep project-level templates in website/templates.
        "DIRS": [BASE_DIR / "website" / "templates"],

        # APP_DIRS=True means Django also looks for templates inside each app:
        # e.g. website/templates/
        "APP_DIRS": True,

        # Context processors inject useful variables into every template.
        "OPTIONS": {
            "context_processors": [
                # Adds "request" to templates (needed for many template patterns).
                "django.template.context_processors.request",

                # Adds user/auth variables (user, perms).
                "django.contrib.auth.context_processors.auth",

                # Adds messages framework support (success/error banners).
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# WSGI application for running under classic web servers (Gunicorn/uWSGI/IIS WSGI bridge, etc.)
WSGI_APPLICATION = "tradegate.wsgi.application"

# =========================
# 7) Database
# =========================
# Database configuration.
# SQLite is perfect for dev; for production you’ll typically use PostgreSQL.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# =========================
# 8) Password validation
# =========================
# Security rules for passwords (helps prevent weak passwords).
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =========================
# 9) Internationalization
# =========================
# Language/timezone settings.
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# =========================
# 10) Static files (CSS/JS/images)
# =========================
# STATIC_URL is the URL prefix for static assets.
STATIC_URL = "static/"

# STATICFILES_DIRS tells Django where to look for additional static files during development.
# This is where your app-level static folder lives.
STATICFILES_DIRS = [BASE_DIR / "website" / "static"]

# =========================
# 11) Email (optional)
# =========================
# These are commented out but left here for later.
# In development, console backend prints emails to the terminal.
#
# DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@tradegate.local")
# CONTACT_RECEIVER_EMAIL = os.getenv("CONTACT_RECEIVER_EMAIL", "you@example.com")
#
# EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
#
# If you switch to SMTP later, set EMAIL_BACKEND to:
# django.core.mail.backends.smtp.EmailBackend
# EMAIL_HOST = os.getenv("EMAIL_HOST", "")
# EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
# EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
# EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"

