"""
Django settings for tradegate project.

Generated by 'django-admin startproject' using Django 6.0.
"""

from pathlib import Path
import os

# =========================
# 1) Base paths
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================
# 2) Environment loading
# =========================
# Local dev: load .env from project root (same folder as manage.py).
# Production: systemd will load EnvironmentFile=/srv/tradegate/.env, so dotenv is optional.
try:
    from dotenv import load_dotenv  # type: ignore
    load_dotenv(BASE_DIR / ".env")
except Exception:
    pass

def env(key: str, default: str = "") -> str:
    return os.getenv(key, default)

def env_bool(key: str, default: bool = False) -> bool:
    val = os.getenv(key)
    if val is None:
        return default
    return val.strip().lower() in ("1", "true", "yes", "on")

def env_list(key: str, default: str = "") -> list[str]:
    raw = os.getenv(key, default)
    return [x.strip() for x in raw.split(",") if x.strip()]

# =========================
# 3) Core security settings
# =========================
# In production, you MUST set DJANGO_SECRET_KEY in /srv/tradegate/.env
SECRET_KEY = env("DJANGO_SECRET_KEY", "unsafe-dev-secret-key-change-me")
DEBUG = env_bool("DJANGO_DEBUG", True)

# Hosts allowed to serve the site.
# Production example:
# DJANGO_ALLOWED_HOSTS=31.97.76.102,tradegate.yourdomain.com
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost")

# If you set HTTPS later, add:
# DJANGO_CSRF_TRUSTED_ORIGINS=https://tradegate.yourdomain.com
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", "")

# =========================
# 4) Application definition
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "django.contrib.sites",

    "website",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tradegate.urls"

# =========================
# 5) Templates
# =========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "website" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tradegate.wsgi.application"

# =========================
# 6) Database
# =========================
# Local default: SQLite
# Production: PostgreSQL if DB_NAME is provided in environment.
DB_NAME = env("DB_NAME", "")
if DB_NAME:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": DB_NAME,
            "USER": env("DB_USER", ""),
            "PASSWORD": env("DB_PASSWORD", ""),
            "HOST": env("DB_HOST", "127.0.0.1"),
            "PORT": env("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# =========================
# 7) Password validation
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =========================
# 8) Internationalization
# =========================
LANGUAGE_CODE = env("DJANGO_LANGUAGE_CODE", "en-us")
TIME_ZONE = env("DJANGO_TIME_ZONE", "UTC")
USE_I18N = True
USE_TZ = True

# =========================
# 9) Static & Media
# =========================
# Nginx will serve /static/ and /media/ in production
STATIC_URL = "/static/"
MEDIA_URL = "/media/"

# Dev: app static directory
STATICFILES_DIRS = [BASE_DIR / "website" / "static"]

# Prod: collected static output
# Matches our VPS folder design: /srv/tradegate/staticfiles
STATIC_ROOT = env("DJANGO_STATIC_ROOT", "/srv/tradegate/staticfiles")

# Prod: uploaded media
MEDIA_ROOT = env("DJANGO_MEDIA_ROOT", "/srv/tradegate/media")

# =========================
# 10) Sites framework
# =========================
SITE_ID = int(env("DJANGO_SITE_ID", "1"))

# =========================
# 11) Production hardening (only when DEBUG=False)
# =========================
if not DEBUG:
    # Turn these on once you have HTTPS working (Certbot)
    SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", False)

    # HSTS (only set when HTTPS is confirmed)
    SECURE_HSTS_SECONDS = int(env("DJANGO_SECURE_HSTS_SECONDS", "0"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
    SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)

    SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", False)
    CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", False)

    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # If HTTPS terminates at Nginx and Nginx passes X-Forwarded-Proto
    if env_bool("DJANGO_SECURE_PROXY_SSL_HEADER", False):
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# =========================
# 12) Logging (simple console logging)
# =========================
LOG_LEVEL = env("DJANGO_LOG_LEVEL", "INFO")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {"handlers": ["console"], "level": LOG_LEVEL},
}

# =========================
# 13) Default primary key
# =========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================
# 14) Email (optional placeholders)
# =========================
# DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", "no-reply@tradegate.local")
# CONTACT_RECEIVER_EMAIL = env("CONTACT_RECEIVER_EMAIL", "you@example.com")
# EMAIL_BACKEND = env("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
# EMAIL_HOST = env("EMAIL_HOST", "")
# EMAIL_PORT = int(env("EMAIL_PORT", "587"))
# EMAIL_HOST_USER = env("EMAIL_HOST_USER", "")
# EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", "")
# EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)


