"""Static marketing content for SEO landing pages and homepage opportunity cards.

Kept outside settings/deployment code so the site can be upgraded safely without
changing environment-specific configuration.
"""

SERVICE_PAGES = {
    "trade-fair-representation-germany": {
        "slug": "trade-fair-representation-germany",
        "service_code": "trade_fair",
        "kicker": "Trade fair representation Germany",
        "title": "Trade Fair Representation in Germany for International SMEs",
        "subtitle": "Attend German and EU trade fairs without sending a full team. TradeGate represents your company, captures qualified leads, documents conversations, and manages follow-up from Leipzig.",
        "primary_keyword": "trade fair representation Germany",
        "meta_title": "Trade Fair Representation Germany | TradeGate Consultants",
        "meta_description": "Germany trade fair representation for international SMEs: booth support, visitor outreach, lead capture, event reporting and follow-up from Leipzig.",
        "hero_badges": ["Germany-based", "Lead capture", "Photos + report", "Follow-up support"],
        "pain_points": [
            "You want EU exposure but travel, hotels and staff costs are high.",
            "You need someone on the ground who understands German business expectations.",
            "You do not only want photos from an event — you want useful contacts and next steps.",
        ],
        "deliverables": [
            "Pre-event briefing and target visitor/profile definition",
            "Trade fair attendance or booth support under your agreed brief",
            "Lead list with notes, contact details where available, and qualification remarks",
            "Photos, short clips and practical event observations",
            "Post-event summary report and recommended follow-up actions",
        ],
        "process": [
            ("Brief", "We define your offer, target buyers, event objective and must-meet contacts."),
            ("Represent", "We attend or support the event professionally and collect structured information."),
            ("Report", "You receive practical deliverables, not vague impressions."),
            ("Follow up", "We help convert interest into calls, introductions or partner discussions."),
        ],
        "faq": [
            ("Can you represent us if we are not travelling to Germany?", "Yes. The service is designed for companies that need a credible local presence without sending a full delegation."),
            ("Do you sell directly on our behalf?", "We can support lead generation, introductions and follow-up. Commercial commitments are agreed case by case and documented clearly."),
            ("What kind of companies is this for?", "Export-ready SMEs, manufacturers, food and beverage producers, tourism bodies, technology firms and service companies preparing for the German or EU market."),
        ],
        "related": ["find-business-partners-germany", "trade-fair-follow-up-lead-management", "germany-market-entry-support"],
    },
    "find-business-partners-germany": {
        "slug": "find-business-partners-germany",
        "service_code": "scouting",
        "kicker": "Partner search Germany",
        "title": "Find Business Partners and Distributors in Germany",
        "subtitle": "TradeGate helps international SMEs identify, approach and qualify potential distributors, resellers, sourcing partners and strategic contacts in Germany and the EU.",
        "primary_keyword": "find business partners Germany",
        "meta_title": "Find Business Partners in Germany | TradeGate Consultants",
        "meta_description": "Partner and distributor search in Germany for international SMEs: target mapping, outreach support, qualification and follow-up.",
        "hero_badges": ["Distributor search", "B2B outreach", "Germany/EU", "Qualified shortlist"],
        "pain_points": [
            "You do not know which German companies are relevant for your product or service.",
            "Cold emails without local context often receive no reply.",
            "You need a structured shortlist, not hundreds of unqualified contacts.",
        ],
        "deliverables": [
            "Target partner profile and search criteria",
            "Shortlist of potential distributors, resellers, buyers or strategic partners",
            "Localized approach messaging and outreach support",
            "Qualification notes and prioritization",
            "Next-step recommendations for calls, samples, meetings or events",
        ],
        "process": [
            ("Define", "We clarify your ideal partner, market segment and value proposition."),
            ("Map", "We research and organize potential partners by relevance."),
            ("Approach", "We support outreach with a German/EU market-aware message."),
            ("Qualify", "We separate serious prospects from low-fit contacts."),
        ],
        "faq": [
            ("Can you guarantee distributors?", "No serious consultancy should guarantee a partner without market validation. We can create a structured path to identify and qualify real opportunities."),
            ("Do you contact companies directly?", "Yes, where agreed in the scope. We can support outreach, introduction handling and follow-up."),
            ("Is this only for Germany?", "Germany is the core entry point, but the same structure can support wider EU partner search."),
        ],
        "related": ["distributor-search-germany", "germany-market-entry-support", "eu-local-representative-germany"],
    },
    "germany-market-entry-support": {
        "slug": "germany-market-entry-support",
        "service_code": "scouting",
        "kicker": "Germany / EU market entry",
        "title": "Germany Market Entry Support for International SMEs",
        "subtitle": "A practical bridge into Germany and the EU: positioning, first contacts, trade fair planning, partner search, and local execution support.",
        "primary_keyword": "Germany market entry support",
        "meta_title": "Germany Market Entry Support | TradeGate Consultants",
        "meta_description": "Practical Germany and EU market entry support for SMEs from Africa, the Middle East and Asia: strategy, partner search, trade fairs and local presence.",
        "hero_badges": ["Market entry", "Germany + EU", "SME focused", "Lean execution"],
        "pain_points": [
            "You want to enter Europe but are not ready for a branch office.",
            "You need to understand which entry route is realistic first.",
            "You need action, not a long theoretical market report.",
        ],
        "deliverables": [
            "Market entry starting-point assessment",
            "Recommended route: trade fair, partner search, local representation or staged approach",
            "Localized positioning and practical sales material review",
            "First outreach and opportunity mapping",
            "Clear action plan with realistic next steps",
        ],
        "process": [
            ("Assess", "We review your readiness, offer and target buyers."),
            ("Position", "We shape the message for German/EU business expectations."),
            ("Activate", "We start with a lean, measurable entry activity."),
            ("Scale", "Successful signals become deeper partner and follow-up work."),
        ],
        "faq": [
            ("Do we need an office in Germany first?", "Not necessarily. Many companies can begin with representation, trade fair validation or partner search before committing to a physical office."),
            ("Which regions do you support?", "TradeGate is especially positioned for SMEs from Africa, the Middle East and Asia seeking access to Germany and the EU."),
            ("Can you help with sales?", "We support the path to sales through positioning, partner discovery, qualified leads and follow-up. Sales responsibility and commercial authority are agreed clearly."),
        ],
        "related": ["eu-local-representative-germany", "find-business-partners-germany", "trade-fair-representation-germany"],
    },
    "eu-local-representative-germany": {
        "slug": "eu-local-representative-germany",
        "service_code": "local_presence",
        "kicker": "Local EU presence",
        "title": "Local EU Representative Presence from Germany",
        "subtitle": "Create a credible contact point in Germany without opening an office. TradeGate can support meetings, follow-up, event presence and relationship management from Leipzig.",
        "primary_keyword": "EU local representative Germany",
        "meta_title": "EU Local Representative Germany | TradeGate Consultants",
        "meta_description": "Local EU representative presence for international SMEs: Germany-based contact support, trade fairs, meetings, follow-up and partner coordination.",
        "hero_badges": ["Leipzig-based", "Local contact", "No branch office", "B2B trust"],
        "pain_points": [
            "Prospects prefer a local European contact point.",
            "You are not ready to hire staff or rent an office in Germany.",
            "You need faster follow-up across time zones and business cultures.",
        ],
        "deliverables": [
            "Local contact and coordination support for agreed activities",
            "Meeting attendance or support where appropriate",
            "Follow-up handling after events or partner discussions",
            "Relationship notes and opportunity tracking",
            "Monthly or project-based reporting",
        ],
        "process": [
            ("Scope", "We define what local representation means for your case."),
            ("Set up", "We align communication routes, materials and contact rules."),
            ("Operate", "We support agreed market-facing activities from Germany."),
            ("Report", "You keep visibility on conversations, actions and next steps."),
        ],
        "faq": [
            ("Is this a legal representative service?", "TradeGate provides business representation and market support. Regulated legal representation is clarified separately and may require specialist partners."),
            ("Can this replace a German office?", "For early validation and relationship building, it can be a lean alternative before larger commitments."),
            ("Can you receive visitors or attend meetings?", "Yes, subject to scope, location and scheduling."),
        ],
        "related": ["germany-market-entry-support", "trade-fair-follow-up-lead-management", "find-business-partners-germany"],
    },
    "distributor-search-germany": {
        "slug": "distributor-search-germany",
        "service_code": "distributor_search",
        "kicker": "Distributor search Germany",
        "title": "Distributor Search in Germany for Export-Ready Companies",
        "subtitle": "Move beyond generic directories. TradeGate helps identify, prioritize and approach German distributor candidates that match your industry, product and market readiness.",
        "primary_keyword": "distributor search Germany",
        "meta_title": "Distributor Search Germany | TradeGate Consultants",
        "meta_description": "Distributor search in Germany for export-ready SMEs: target profile, shortlist, outreach support and qualification.",
        "hero_badges": ["Export-ready SMEs", "German distributors", "Shortlist", "Outreach support"],
        "pain_points": [
            "Many distributor lists are outdated or too broad.",
            "German distributors expect clear product information and realistic margins.",
            "You need to know who is worth pursuing first.",
        ],
        "deliverables": [
            "Distributor profile and fit criteria",
            "Prioritized candidate list",
            "Outreach script and localized email support",
            "Response tracking and qualification notes",
            "Recommended follow-up sequence",
        ],
        "process": [
            ("Prepare", "We review your product readiness and distributor fit."),
            ("Research", "We build a focused list around industry and channel logic."),
            ("Engage", "We support first approach and follow-up."),
            ("Qualify", "We identify who deserves deeper discussion."),
        ],
        "faq": [
            ("What do you need from us?", "A clear company profile, product details, website or brochure, target margins if available, and market goals."),
            ("Can you help with food, agriculture or manufacturing?", "Yes, those sectors fit the TradeGate positioning well when export readiness is clear."),
            ("Is this the same as sales agency work?", "It can support sales development, but distributor search is usually a defined project with clear deliverables."),
        ],
        "related": ["find-business-partners-germany", "germany-market-entry-support", "trade-fair-representation-germany"],
    },
    "trade-fair-follow-up-lead-management": {
        "slug": "trade-fair-follow-up-lead-management",
        "service_code": "follow_up",
        "kicker": "Lead follow-up Germany",
        "title": "Trade Fair Follow-up and Lead Management in Germany",
        "subtitle": "After a trade fair, speed and structure matter. TradeGate helps organize leads, follow up professionally, and turn event conversations into real business opportunities.",
        "primary_keyword": "trade fair follow-up Germany",
        "meta_title": "Trade Fair Follow-up Germany | TradeGate Consultants",
        "meta_description": "Trade fair lead follow-up and relationship management in Germany: organize leads, qualify interest, send follow-up and prepare next steps.",
        "hero_badges": ["Post-event follow-up", "Lead qualification", "German market", "Next steps"],
        "pain_points": [
            "Many trade fair leads go cold because follow-up is slow or unclear.",
            "Your team may be outside Europe and busy after the event.",
            "You need structured next steps, not a stack of business cards.",
        ],
        "deliverables": [
            "Lead organization and priority tagging",
            "Follow-up email support and response tracking",
            "Meeting scheduling support where agreed",
            "Opportunity notes and recommended next actions",
            "Summary report for management",
        ],
        "process": [
            ("Organize", "We turn raw contacts into a usable lead list."),
            ("Prioritize", "We separate hot prospects, information requests and low-fit contacts."),
            ("Follow up", "We help send timely, professional follow-ups."),
            ("Convert", "We prepare next-step calls, samples, partner talks or proposals."),
        ],
        "faq": [
            ("Can you help after an event we attended ourselves?", "Yes. If you have leads or notes, we can help structure the follow-up process."),
            ("Do you write follow-up emails?", "Yes, depending on the scope we can prepare or support follow-up communication."),
            ("Can this be combined with event representation?", "Yes. The strongest model is representation plus structured follow-up."),
        ],
        "related": ["trade-fair-representation-germany", "eu-local-representative-germany", "find-business-partners-germany"],
    },
}

SERVICE_NAV = [
    ("Trade Fair Representation", "trade-fair-representation-germany"),
    ("Partner Search", "find-business-partners-germany"),
    ("Market Entry Support", "germany-market-entry-support"),
    ("EU Local Presence", "eu-local-representative-germany"),
    ("Distributor Search", "distributor-search-germany"),
    ("Lead Follow-up", "trade-fair-follow-up-lead-management"),
]

DEFAULT_OPPORTUNITIES = [
    {
        "title": "Fruit Logistica Berlin",
        "slug": "fruit-logistica-berlin",
        "city_country": "Berlin, Germany",
        "date_label": "Food export · fresh produce",
        "industry": "Agriculture, food & retail",
        "summary": "A strong entry point for exporters seeking importers, distributors and retail conversations in Europe.",
        "cta_label": "Request representation",
        "cta_url": "/contact/?service=trade_fair&event=fruit-logistica-berlin#contact-form",
        "visual_label": "Berlin",
    },
    {
        "title": "Anuga Cologne",
        "slug": "anuga-cologne",
        "city_country": "Cologne, Germany",
        "date_label": "Food & beverage distribution",
        "industry": "FMCG, ingredients, private label",
        "summary": "Useful for food and beverage producers preparing for German/EU buyers and distribution partners.",
        "cta_label": "Discuss market entry",
        "cta_url": "/contact/?service=scouting&event=anuga-cologne#contact-form",
        "visual_label": "Köln",
    },
    {
        "title": "Hannover Messe",
        "slug": "hannover-messe",
        "city_country": "Hannover, Germany",
        "date_label": "Industry, machinery & technology",
        "industry": "Manufacturing, energy, automation",
        "summary": "Ideal for manufacturers and technology firms seeking visibility, partners and industrial buyers.",
        "cta_label": "Find partners",
        "cta_url": "/contact/?service=scouting&event=hannover-messe#contact-form",
        "visual_label": "HMI",
    },
]
